### ISSUE TITLE
Error trying to update environment variables

### ISSUE THREAD

**Issue by thekal** [boroivanov/ecs-tools#25]
This is on a new laptop with a fresh setup, so not sure if my environment is configured properly

```
$ ecs service env staging svod-be V2_CACHE_URL='https://rtv2-video.roosterteeth.com' V3_CACHE_URL='https://rtv3-video.roosterteeth.com'
Current task definition for staging svod-be: svod-be-staging:141

==> Container: svod-be
- V2_CACHE_URL=https://rtv2-roosterteeth.akamaized.net
+ V2_CACHE_URL=https://rtv2-video.roosterteeth.com
- V3_CACHE_URL=https://rtv3-roosterteeth.akamaized.net
+ V3_CACHE_URL=https://rtv3-video.roosterteeth.com

Do you want to create a new task definition revision? y
Traceback (most recent call last):
  File "/usr/local/bin/ecs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ecstools/commands/service/env.py", line 52, in env
    td = srv.register_task_definition(td_dict)
TypeError: register_task_definition() missing 1 required positional argument: 'verbose'
```

```
$ ecs --version
0.1.6
```

**Comment by boroivanov** [comment]
Fixed in v0.1.7
